[main]
    separator = "-"
    enableDarkMode = true
    enableLanguageSelectionStorage = false
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    endorse = true
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    [main.internalLinks]
        validate = true
    [main.externalLinks]
        cue = false
        tab = false
    [main.build]
        transpiler = "libsass"

[navigation]
    anchor = true
    logo = ""
    color = "body"
    fixed = true
    overlay = false
    overlayMode = "dark"
    horizontal = false
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"

[home]
    fullCover = false
    centerHeadline = true
    style = ""
    [home.feature]
        orientation = "horizontal"
        color = "primary"
        width = 100
        align = "start"
