baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Amronos - Website'
[module]
    [[module.imports]]
        path = 'github.com/gethinode/hinode'
    [[module.mounts]]
        source = 'content'
        target = 'content'
